baseURL = 'https://uzukidd.github.io'
title = 'Zero'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zero'

    [languages.en.params]
      author = "Luo CHENG"
      description = "Master Student in ISCAS and CAS. Focusing on Automatic Driving and AI alignment."
      motto = "*Radio Silence*"
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Honors and Awards'
      url = '#honors-and-awards'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 5

[params]
  profilePicture = "images/profile.jpg"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/"
    icon = "fab fa-github"
  [[params.social]]
    name = "google-scholar"
    url = "https://scholar.google.com/"
    icon = "fab fa-google-scholar"
  [[params.social]]
    name = "email"
    url = "mailto:example@example.com"
    icon = "fas fa-envelope"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/"
    icon = "fab fa-linkedin"
  [[params.social]]
    name = "zhihu"
    url = "https://zhihu.com/"
    icon = "fab fa-zhihu"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
